"""Reproducible Markdown, CSV and JSON research reports."""

import json
import re
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass, is_dataclass
from datetime import date, datetime
from enum import Enum
from pathlib import Path
from typing import Any, Literal

import numpy as np
import pandas as pd

from app.services.reporting.metrics import (
    PerformanceMetrics,
    aggregate_trade_performance,
    calculate_performance_metrics,
    drawdown_series,
    monthly_returns,
    regime_distribution,
    regime_transition_matrix,
)

CheckStatus = Literal["PASS", "FAIL", "NOT_EVALUATED"]


@dataclass(frozen=True)
class AcceptanceCheck:
    """One auditable acceptance decision with the observed value and rule."""

    name: str
    status: CheckStatus
    observed: Any
    criterion: str
    reason: str


@dataclass(frozen=True)
class AcceptanceAssessment:
    """Overall verdict; missing evidence can never produce PASS."""

    overall: Literal["PASS", "FAIL", "INSUFFICIENT_EVIDENCE"]
    checks: tuple[AcceptanceCheck, ...]


@dataclass(frozen=True)
class ReportArtifacts:
    """Paths generated by :func:`generate_report`."""

    markdown: Path
    json: Path
    csv: dict[str, Path]


def _check(
    name: str,
    value: Any,
    passed: bool | None,
    criterion: str,
    reason: str,
) -> AcceptanceCheck:
    status: CheckStatus = "NOT_EVALUATED" if passed is None else ("PASS" if passed else "FAIL")
    return AcceptanceCheck(name, status, value, criterion, reason)


def evaluate_legacy_acceptance(
    *,
    oos_return: float | None = None,
    walk_forward_returns: Sequence[float] | None = None,
    fee_stress_return: float | None = None,
    slippage_stress_return: float | None = None,
    leave_one_period_out_returns: Sequence[float] | None = None,
    symbol_returns: Mapping[str, float] | None = None,
    maximum_drawdown: float | None = None,
    maximum_drawdown_limit: float = 0.08,
    parameters_stable: bool | None = None,
    ruin_probability: float | None = None,
    maximum_ruin_probability: float = 0.01,
    minimum_order_feasible: bool | None = None,
    pbo: float | None = None,
    deflated_sharpe_passes: bool | None = None,
) -> AcceptanceAssessment:
    """Apply conservative research gates without filling absent evidence with success."""

    if not 0 < maximum_drawdown_limit < 1:
        raise ValueError("maximum_drawdown_limit must be between zero and one")
    if not 0 <= maximum_ruin_probability < 1:
        raise ValueError("maximum_ruin_probability must be between zero and one")
    checks: list[AcceptanceCheck] = []
    checks.append(
        _check(
            "out_of_sample_positive",
            oos_return,
            None if oos_return is None else oos_return > 0,
            "untouched out-of-sample total return > 0",
            "final evaluation must not reuse training or validation observations",
        )
    )
    if walk_forward_returns is None:
        walk_forward_value: Any = None
        walk_forward_pass: bool | None = None
    else:
        walk_forward = np.asarray(walk_forward_returns, dtype=np.float64)
        if not walk_forward.size or not np.isfinite(walk_forward).all():
            raise ValueError("walk_forward_returns must be a non-empty finite sequence")
        walk_forward_value = float(np.mean(walk_forward > 0))
        walk_forward_pass = bool(walk_forward_value > 0.5)
    checks.append(
        _check(
            "walk_forward_majority_positive",
            walk_forward_value,
            walk_forward_pass,
            "strictly more than half of walk-forward OOS windows have positive return",
            "all windows are counted, including losing windows",
        )
    )
    checks.append(
        _check(
            "fee_stress",
            fee_stress_return,
            None if fee_stress_return is None else fee_stress_return > 0,
            "total return remains positive with fees multiplied by 1.5",
            "stressed costs must be recomputed through the fill ledger",
        )
    )
    checks.append(
        _check(
            "slippage_stress",
            slippage_stress_return,
            None if slippage_stress_return is None else slippage_stress_return > 0,
            "total return remains positive with slippage multiplied by 2",
            "a positive threshold is more conservative than merely avoiding bankruptcy",
        )
    )
    if leave_one_period_out_returns is None:
        leave_out_value: Any = None
        leave_out_pass: bool | None = None
    else:
        leave_out = np.asarray(leave_one_period_out_returns, dtype=np.float64)
        if not leave_out.size or not np.isfinite(leave_out).all():
            raise ValueError("leave_one_period_out_returns must be non-empty and finite")
        leave_out_value = float(np.min(leave_out))
        leave_out_pass = bool(np.all(leave_out > 0))
    checks.append(
        _check(
            "leave_one_period_out",
            leave_out_value,
            leave_out_pass,
            "return stays positive after excluding each evaluation period in turn",
            "the observed value is the worst leave-one-period-out result",
        )
    )
    if symbol_returns is None:
        symbol_value: Any = None
        symbol_pass: bool | None = None
    else:
        if len(symbol_returns) < 2 or not all(
            np.isfinite(value) for value in symbol_returns.values()
        ):
            raise ValueError("symbol_returns requires at least two finite symbol results")
        positive = {name: value for name, value in symbol_returns.items() if value > 0}
        positive_total = sum(positive.values())
        concentration = max(positive.values()) / positive_total if positive_total > 0 else 1.0
        symbol_value = {"positive_symbols": len(positive), "profit_concentration": concentration}
        symbol_pass = len(positive) >= 2 and concentration <= 0.7
    checks.append(
        _check(
            "symbol_diversification",
            symbol_value,
            symbol_pass,
            "at least two profitable symbols and no symbol above 70% of positive contribution",
            "losses are retained; concentration uses positive contribution only",
        )
    )
    checks.extend(
        [
            _check(
                "maximum_drawdown",
                maximum_drawdown,
                None if maximum_drawdown is None else maximum_drawdown <= maximum_drawdown_limit,
                f"maximum drawdown <= {maximum_drawdown_limit:.2%}",
                "the limit is configured before evaluation",
            ),
            _check(
                "parameter_plateau",
                parameters_stable,
                parameters_stable,
                "selected parameters pass local plateau stability checks",
                "an isolated best parameter is rejected",
            ),
            _check(
                "risk_of_ruin",
                ruin_probability,
                None if ruin_probability is None else ruin_probability <= maximum_ruin_probability,
                f"Monte Carlo ruin probability <= {maximum_ruin_probability:.2%}",
                "net returns and fixed seeded block resampling are required",
            ),
            _check(
                "minimum_order_feasibility",
                minimum_order_feasible,
                minimum_order_feasible,
                "the intended capital can place exchange-compliant minimum orders",
                "fees and executable trade count must be included in the feasibility study",
            ),
            _check(
                "probability_of_backtest_overfitting",
                pbo,
                None if pbo is None else pbo < 0.5,
                "PBO estimate < 50%",
                "the number and range of all tried configurations must be disclosed",
            ),
            _check(
                "deflated_sharpe",
                deflated_sharpe_passes,
                deflated_sharpe_passes,
                "Deflated Sharpe probability meets its predeclared confidence threshold",
                "the trial count includes discarded configurations",
            ),
        ]
    )
    if any(item.status == "FAIL" for item in checks):
        overall: Literal["PASS", "FAIL", "INSUFFICIENT_EVIDENCE"] = "FAIL"
    elif any(item.status == "NOT_EVALUATED" for item in checks):
        overall = "INSUFFICIENT_EVIDENCE"
    else:
        overall = "PASS"
    return AcceptanceAssessment(overall=overall, checks=tuple(checks))


def _jsonable(value: Any) -> Any:
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        return value if np.isfinite(value) else None
    if isinstance(value, np.generic):
        return _jsonable(value.item())
    if isinstance(value, (datetime, date, pd.Timestamp)):
        return value.isoformat()
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, Enum):
        return value.value
    if is_dataclass(value) and not isinstance(value, type):
        return _jsonable(asdict(value))
    if isinstance(value, pd.DataFrame):
        return _jsonable(value.reset_index().to_dict(orient="records"))
    if isinstance(value, pd.Series):
        return _jsonable(value.to_list())
    if isinstance(value, Mapping):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, np.ndarray):
        return _jsonable(value.tolist())
    if isinstance(value, Sequence):
        return [_jsonable(item) for item in value]
    if pd.isna(value):
        return None
    return str(value)


def _format_value(value: Any) -> str:
    if value is None or (isinstance(value, float) and not np.isfinite(value)):
        return "N/A"
    if isinstance(value, float):
        return f"{value:.8g}"
    return str(value).replace("|", "\\|").replace("\n", " ")


def _markdown_table(frame: pd.DataFrame, *, maximum_rows: int | None = None) -> str:
    if frame.empty:
        return "_No data available._"
    display = frame if maximum_rows is None else frame.head(maximum_rows)
    columns = [str(column) for column in display.columns]
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for row in display.itertuples(index=False, name=None):
        lines.append("| " + " | ".join(_format_value(value) for value in row) + " |")
    if maximum_rows is not None and len(frame) > maximum_rows:
        lines.append(f"\n_Full table has {len(frame)} rows and is included in CSV and JSON._")
    return "\n".join(lines)


def _frame_with_index(series: pd.Series, value_name: str) -> pd.DataFrame:
    index_name = series.index.name or (
        "timestamp" if isinstance(series.index, pd.DatetimeIndex) else "index"
    )
    return pd.DataFrame({index_name: series.index, value_name: series.to_numpy(dtype=np.float64)})


def _diagnostics(
    metrics: PerformanceMetrics,
    tables: Mapping[str, pd.DataFrame],
) -> tuple[str, ...]:
    diagnostics: list[str] = []
    monthly = tables.get("monthly_returns", pd.DataFrame())
    if not monthly.empty:
        losing = monthly.loc[monthly["return"] < 0, "month"]
        diagnostics.append(f"Losing calendar months: {len(losing)} of {len(monthly)}.")
    regimes = tables.get("regime_performance", pd.DataFrame())
    if not regimes.empty:
        losing_regimes = regimes.loc[regimes["total_pnl"] < 0, "regime"].astype(str).tolist()
        diagnostics.append(
            "Losing regimes: "
            + (", ".join(losing_regimes) if losing_regimes else "none observed")
            + "."
        )
    symbols = tables.get("symbol_performance", pd.DataFrame())
    if not symbols.empty:
        positives = symbols.loc[symbols["total_pnl"] > 0, "total_pnl"]
        concentration = float(positives.max() / positives.sum()) if not positives.empty else 1.0
        diagnostics.append(f"Largest symbol share of positive PnL: {concentration:.2%}.")
    known_costs = [metrics.fee_cost, metrics.slippage_cost, metrics.market_impact_cost]
    if all(value is None for value in known_costs):
        diagnostics.append(
            "Execution-cost fields were unavailable; cost robustness is not established."
        )
    if metrics.funding_pnl is None:
        diagnostics.append("Funding PnL was unavailable and was not assumed to be zero.")
    diagnostics.append(
        "Statistical significance and production readiness require separate OOS, walk-forward, "
        "cost-stress and overfitting evidence. This report does not infer them from positive "
        "return."
    )
    return tuple(diagnostics)


def _safe_table_name(name: str) -> str:
    if not re.fullmatch(r"[a-z0-9][a-z0-9_-]*", name):
        raise ValueError(f"unsafe report table name: {name!r}")
    return name


def _atomic_text(path: Path, content: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def generate_report(
    output_directory: str | Path,
    *,
    equity_curve: pd.Series,
    trades: pd.DataFrame | None = None,
    returns: pd.Series | None = None,
    exposure_series: pd.Series | None = None,
    regimes: Sequence[str] | pd.Series | None = None,
    periods_per_year: float = 365.0,
    assessment: AcceptanceAssessment | None = None,
    metadata: Mapping[str, Any] | None = None,
    walk_forward_results: pd.DataFrame | None = None,
    parameter_sensitivity: pd.DataFrame | None = None,
    monte_carlo_summary: Mapping[str, Any] | None = None,
    extra_tables: Mapping[str, pd.DataFrame] | None = None,
) -> ReportArtifacts:
    """Write complete research artifacts without filtering unfavorable rows.

    The JSON document contains all CSV tables. The Markdown document emphasizes
    diagnostics and acceptance failures; detailed trade rows remain in CSV/JSON to
    keep the human-readable report manageable without discarding evidence.
    """

    destination = Path(output_directory).expanduser().resolve()
    destination.mkdir(parents=True, exist_ok=True)
    trade_frame = pd.DataFrame() if trades is None else trades.copy()
    metrics = calculate_performance_metrics(
        equity_curve,
        returns=returns,
        trades=None if trade_frame.empty else trade_frame,
        exposure_series=exposure_series,
        periods_per_year=periods_per_year,
    )
    equity_frame = _frame_with_index(equity_curve.astype(float), "equity")
    drawdown_frame = _frame_with_index(drawdown_series(equity_curve), "drawdown")
    tables: dict[str, pd.DataFrame] = {
        "summary_metrics": pd.DataFrame([metrics.to_dict()]),
        "equity_curve": equity_frame,
        "drawdown_curve": drawdown_frame,
        "trades": trade_frame,
        "execution_costs": pd.DataFrame(
            {
                "component": ["fees", "funding_pnl", "slippage", "market_impact"],
                "value": [
                    metrics.fee_cost,
                    metrics.funding_pnl,
                    metrics.slippage_cost,
                    metrics.market_impact_cost,
                ],
            }
        ),
    }
    if isinstance(equity_curve.index, pd.DatetimeIndex):
        tables["monthly_returns"] = monthly_returns(equity_curve)
    else:
        tables["monthly_returns"] = pd.DataFrame(columns=["month", "return"])
    aggregates = aggregate_trade_performance(trade_frame) if not trade_frame.empty else {}
    for dimension in ("regime", "strategy", "symbol"):
        tables[f"{dimension}_performance"] = aggregates.get(dimension, pd.DataFrame())
    if regimes is None:
        tables["regime_distribution"] = pd.DataFrame(columns=["regime", "count", "fraction"])
        tables["regime_transition_matrix"] = pd.DataFrame()
    else:
        tables["regime_distribution"] = regime_distribution(regimes)
        tables["regime_transition_matrix"] = regime_transition_matrix(regimes).reset_index()
    tables["walk_forward_results"] = (
        pd.DataFrame() if walk_forward_results is None else walk_forward_results.copy()
    )
    tables["parameter_sensitivity"] = (
        pd.DataFrame() if parameter_sensitivity is None else parameter_sensitivity.copy()
    )
    if monte_carlo_summary is not None:
        tables["monte_carlo_summary"] = pd.DataFrame([_jsonable(monte_carlo_summary)])
    if extra_tables is not None:
        for name, frame in extra_tables.items():
            safe_name = _safe_table_name(name)
            if safe_name in tables:
                raise ValueError(f"extra table would overwrite built-in table: {safe_name}")
            tables[safe_name] = frame.copy()

    csv_paths: dict[str, Path] = {}
    for name, frame in tables.items():
        safe_name = _safe_table_name(name)
        path = destination / f"{safe_name}.csv"
        frame.to_csv(path, index=False)
        csv_paths[safe_name] = path

    diagnostics = _diagnostics(metrics, tables)
    resolved_assessment = assessment or AcceptanceAssessment("INSUFFICIENT_EVIDENCE", ())
    payload = {
        "schema_version": "research-report-1.0",
        "metadata": dict(metadata or {}),
        "metrics": metrics.to_dict(),
        "acceptance": asdict(resolved_assessment),
        "diagnostics": diagnostics,
        "monte_carlo": dict(monte_carlo_summary or {}),
        "tables": {name: frame for name, frame in tables.items()},
    }
    json_path = destination / "report.json"
    _atomic_text(
        json_path,
        json.dumps(
            _jsonable(payload), ensure_ascii=False, indent=2, allow_nan=False, sort_keys=True
        ),
    )

    metric_table = pd.DataFrame(
        {"metric": list(metrics.to_dict()), "value": list(metrics.to_dict().values())}
    )
    if resolved_assessment.checks:
        acceptance_table = pd.DataFrame([asdict(item) for item in resolved_assessment.checks])
    else:
        acceptance_table = pd.DataFrame(
            [
                {
                    "name": "validation_evidence",
                    "status": "NOT_EVALUATED",
                    "observed": None,
                    "criterion": "all predeclared acceptance gates evaluated",
                    "reason": "no acceptance assessment was supplied",
                }
            ]
        )
    sections = [
        "# CryptBot Research Report",
        "",
        f"Overall acceptance verdict: **{resolved_assessment.overall}**",
        "",
        "A positive backtest alone is not treated as evidence of a reproducible edge.",
        "",
        "## Performance metrics",
        "",
        _markdown_table(metric_table),
        "",
        "## Acceptance gates",
        "",
        _markdown_table(acceptance_table),
        "",
        "## Adverse-result diagnostics",
        "",
        *(f"- {item}" for item in diagnostics),
    ]
    for title, name in (
        ("Monthly returns", "monthly_returns"),
        ("Regime performance", "regime_performance"),
        ("Strategy performance", "strategy_performance"),
        ("Symbol performance", "symbol_performance"),
        ("Regime distribution", "regime_distribution"),
        ("Regime transition matrix", "regime_transition_matrix"),
        ("Walk-forward results", "walk_forward_results"),
        ("Parameter sensitivity", "parameter_sensitivity"),
        ("Execution cost breakdown", "execution_costs"),
    ):
        sections.extend(["", f"## {title}", "", _markdown_table(tables[name], maximum_rows=100)])
    sections.extend(
        [
            "",
            "## Reproducibility notes",
            "",
            "- All trade rows and table rows are stored in CSV and JSON; "
            "no losing rows are filtered.",
            "- Missing cost fields remain N/A and are never interpreted as zero cost.",
            "- Resampling seeds, trial counts, split boundaries and parameter search ranges "
            "must be retained.",
            "- Live trading remains ineligible until every required gate is evaluated and passes.",
            "",
        ]
    )
    markdown_path = destination / "report.md"
    _atomic_text(markdown_path, "\n".join(sections))
    return ReportArtifacts(markdown=markdown_path, json=json_path, csv=csv_paths)
