"""continuous paper operations

Revision ID: 0013_continuous_paper
Revises: 0012_orderbook_recovery
Create Date: 2026-07-15 01:41:16.698028
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013_continuous_paper"
down_revision: str | Sequence[str] | None = "0012_orderbook_recovery"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operational_runs",
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("collector_healthy", sa.Boolean(), nullable=False),
        sa.Column("last_snapshot_id", sa.String(length=160), nullable=True),
        sa.Column("last_research_run_ids_json", sa.Text(), nullable=False),
        sa.Column("signals_paused_reason", sa.String(length=500), nullable=True),
        sa.Column("failure_reason", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_operational_runs_status"), "operational_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_operational_runs_updated_at"), "operational_runs", ["updated_at"], unique=False
    )
    op.create_table(
        "paper_attribution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("portfolio_id", sa.String(length=80), nullable=False),
        sa.Column("attribution_date", sa.String(length=10), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "portfolio_id", "attribution_date"),
    )
    op.create_index(
        op.f("ix_paper_attribution_attribution_date"),
        "paper_attribution",
        ["attribution_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_attribution_portfolio_id"),
        "paper_attribution",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "paper_cash_ledger",
        sa.Column("entry_id", sa.String(length=160), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("portfolio_id", sa.String(length=80), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("entry_type", sa.String(length=80), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reference_id", sa.String(length=160), nullable=True),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_index(
        op.f("ix_paper_cash_ledger_occurred_at"), "paper_cash_ledger", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_paper_cash_ledger_portfolio_id"),
        "paper_cash_ledger",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "paper_daily_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("portfolio_id", sa.String(length=80), nullable=False),
        sa.Column("metric_date", sa.String(length=10), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "portfolio_id", "metric_date"),
    )
    op.create_index(
        op.f("ix_paper_daily_metrics_metric_date"),
        "paper_daily_metrics",
        ["metric_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_daily_metrics_portfolio_id"),
        "paper_daily_metrics",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "paper_funding_ledger",
        sa.Column("entry_id", sa.String(length=160), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("portfolio_id", sa.String(length=80), nullable=False),
        sa.Column("venue", sa.String(length=40), nullable=False),
        sa.Column("instrument", sa.String(length=100), nullable=False),
        sa.Column("rate", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_index(
        op.f("ix_paper_funding_ledger_occurred_at"),
        "paper_funding_ledger",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_funding_ledger_portfolio_id"),
        "paper_funding_ledger",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "paper_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("portfolio_id", sa.String(length=80), nullable=False),
        sa.Column("venue", sa.String(length=40), nullable=False),
        sa.Column("instrument", sa.String(length=100), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "portfolio_id", "venue", "instrument"),
    )
    op.create_index(
        op.f("ix_paper_positions_data_snapshot_id"),
        "paper_positions",
        ["data_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_positions_portfolio_id"), "paper_positions", ["portfolio_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_positions_research_run_id"),
        "paper_positions",
        ["research_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_positions_strategy_id"), "paper_positions", ["strategy_id"], unique=False
    )
    op.create_table(
        "paper_risk_events",
        sa.Column("event_id", sa.String(length=160), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("portfolio_id", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("blocks_new_signals", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_paper_risk_events_event_type"), "paper_risk_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_paper_risk_events_occurred_at"), "paper_risk_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_paper_risk_events_portfolio_id"),
        "paper_risk_events",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "paper_signals",
        sa.Column("signal_id", sa.String(length=160), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("decision_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("instrument", sa.String(length=100), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
        sa.Column("signal_hash", sa.String(length=64), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("signal_id"),
    )
    op.create_index(
        op.f("ix_paper_signals_data_snapshot_id"),
        "paper_signals",
        ["data_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_signals_decision_time"), "paper_signals", ["decision_time"], unique=False
    )
    op.create_index(
        op.f("ix_paper_signals_instrument"), "paper_signals", ["instrument"], unique=False
    )
    op.create_index(
        op.f("ix_paper_signals_research_run_id"), "paper_signals", ["research_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_signals_strategy_id"), "paper_signals", ["strategy_id"], unique=False
    )
    op.create_table(
        "strategy_eligibility",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reasons_json", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "strategy_id", "strategy_version"),
    )
    op.create_index(
        op.f("ix_strategy_eligibility_data_snapshot_id"),
        "strategy_eligibility",
        ["data_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_strategy_eligibility_expires_at"),
        "strategy_eligibility",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_strategy_eligibility_research_run_id"),
        "strategy_eligibility",
        ["research_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_strategy_eligibility_status"), "strategy_eligibility", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_strategy_eligibility_strategy_id"),
        "strategy_eligibility",
        ["strategy_id"],
        unique=False,
    )
    op.create_table(
        "paper_orders",
        sa.Column("order_id", sa.String(length=160), nullable=False),
        sa.Column("signal_id", sa.String(length=160), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("portfolio_id", sa.String(length=80), nullable=False),
        sa.Column("venue", sa.String(length=40), nullable=False),
        sa.Column("instrument", sa.String(length=100), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["paper_signals.signal_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_index(
        op.f("ix_paper_orders_data_snapshot_id"), "paper_orders", ["data_snapshot_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_orders_portfolio_id"), "paper_orders", ["portfolio_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_orders_research_run_id"), "paper_orders", ["research_run_id"], unique=False
    )
    op.create_index(op.f("ix_paper_orders_status"), "paper_orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_paper_orders_strategy_id"), "paper_orders", ["strategy_id"], unique=False
    )
    op.create_table(
        "paper_fills",
        sa.Column("fill_id", sa.String(length=160), nullable=False),
        sa.Column("order_id", sa.String(length=160), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_id", sa.String(length=100), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("data_snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("research_run_id", sa.String(length=160), nullable=False),
        sa.Column("portfolio_id", sa.String(length=80), nullable=False),
        sa.Column("venue", sa.String(length=40), nullable=False),
        sa.Column("instrument", sa.String(length=100), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("commit_sha", sa.String(length=80), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["paper_orders.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["operational_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("fill_id"),
    )
    op.create_index(
        op.f("ix_paper_fills_data_snapshot_id"), "paper_fills", ["data_snapshot_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_fills_executed_at"), "paper_fills", ["executed_at"], unique=False
    )
    op.create_index(
        op.f("ix_paper_fills_portfolio_id"), "paper_fills", ["portfolio_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_fills_research_run_id"), "paper_fills", ["research_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_fills_strategy_id"), "paper_fills", ["strategy_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paper_fills_strategy_id"), table_name="paper_fills")
    op.drop_index(op.f("ix_paper_fills_research_run_id"), table_name="paper_fills")
    op.drop_index(op.f("ix_paper_fills_portfolio_id"), table_name="paper_fills")
    op.drop_index(op.f("ix_paper_fills_executed_at"), table_name="paper_fills")
    op.drop_index(op.f("ix_paper_fills_data_snapshot_id"), table_name="paper_fills")
    op.drop_table("paper_fills")
    op.drop_index(op.f("ix_paper_orders_strategy_id"), table_name="paper_orders")
    op.drop_index(op.f("ix_paper_orders_status"), table_name="paper_orders")
    op.drop_index(op.f("ix_paper_orders_research_run_id"), table_name="paper_orders")
    op.drop_index(op.f("ix_paper_orders_portfolio_id"), table_name="paper_orders")
    op.drop_index(op.f("ix_paper_orders_data_snapshot_id"), table_name="paper_orders")
    op.drop_table("paper_orders")
    op.drop_index(op.f("ix_strategy_eligibility_strategy_id"), table_name="strategy_eligibility")
    op.drop_index(op.f("ix_strategy_eligibility_status"), table_name="strategy_eligibility")
    op.drop_index(
        op.f("ix_strategy_eligibility_research_run_id"), table_name="strategy_eligibility"
    )
    op.drop_index(op.f("ix_strategy_eligibility_expires_at"), table_name="strategy_eligibility")
    op.drop_index(
        op.f("ix_strategy_eligibility_data_snapshot_id"), table_name="strategy_eligibility"
    )
    op.drop_table("strategy_eligibility")
    op.drop_index(op.f("ix_paper_signals_strategy_id"), table_name="paper_signals")
    op.drop_index(op.f("ix_paper_signals_research_run_id"), table_name="paper_signals")
    op.drop_index(op.f("ix_paper_signals_instrument"), table_name="paper_signals")
    op.drop_index(op.f("ix_paper_signals_decision_time"), table_name="paper_signals")
    op.drop_index(op.f("ix_paper_signals_data_snapshot_id"), table_name="paper_signals")
    op.drop_table("paper_signals")
    op.drop_index(op.f("ix_paper_risk_events_portfolio_id"), table_name="paper_risk_events")
    op.drop_index(op.f("ix_paper_risk_events_occurred_at"), table_name="paper_risk_events")
    op.drop_index(op.f("ix_paper_risk_events_event_type"), table_name="paper_risk_events")
    op.drop_table("paper_risk_events")
    op.drop_index(op.f("ix_paper_positions_strategy_id"), table_name="paper_positions")
    op.drop_index(op.f("ix_paper_positions_research_run_id"), table_name="paper_positions")
    op.drop_index(op.f("ix_paper_positions_portfolio_id"), table_name="paper_positions")
    op.drop_index(op.f("ix_paper_positions_data_snapshot_id"), table_name="paper_positions")
    op.drop_table("paper_positions")
    op.drop_index(op.f("ix_paper_funding_ledger_portfolio_id"), table_name="paper_funding_ledger")
    op.drop_index(op.f("ix_paper_funding_ledger_occurred_at"), table_name="paper_funding_ledger")
    op.drop_table("paper_funding_ledger")
    op.drop_index(op.f("ix_paper_daily_metrics_portfolio_id"), table_name="paper_daily_metrics")
    op.drop_index(op.f("ix_paper_daily_metrics_metric_date"), table_name="paper_daily_metrics")
    op.drop_table("paper_daily_metrics")
    op.drop_index(op.f("ix_paper_cash_ledger_portfolio_id"), table_name="paper_cash_ledger")
    op.drop_index(op.f("ix_paper_cash_ledger_occurred_at"), table_name="paper_cash_ledger")
    op.drop_table("paper_cash_ledger")
    op.drop_index(op.f("ix_paper_attribution_portfolio_id"), table_name="paper_attribution")
    op.drop_index(op.f("ix_paper_attribution_attribution_date"), table_name="paper_attribution")
    op.drop_table("paper_attribution")
    op.drop_index(op.f("ix_operational_runs_updated_at"), table_name="operational_runs")
    op.drop_index(op.f("ix_operational_runs_status"), table_name="operational_runs")
    op.drop_table("operational_runs")
    # ### end Alembic commands ###
